name: Build Backend y Frontend

on:
  push:
    branches: [ main, master, develop, front_backend/** ]
  pull_request:
    branches: [ main, master, develop, front_backend/** ]

jobs:
  setup:
    name: Instalar dependencias
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.versions.outputs.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

  backend:
    name: Backend - Type Check y Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type Check backend
        run: npx tsc -p backend --noEmit

      - name: Build backend
        run: npm run build:backend

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist

  frontend:
    name: Frontend - Build Vite
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend (Vite)
        run: npm run frontend:build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  summary:
    name: Resumen CI
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Generar resumen
        run: |
          echo "Backend y Frontend construidos correctamente" >> $GITHUB_STEP_SUMMARY


